export const ADD_TASKS = 'ADD_TASKS';
export const REMOVE_TASKS = 'REMOVE_TASKS';
export const SELECT_TASK_TO_WORK = 'SELECT_TASK_TO_WORK';
export const ADD_TIME_WORKED_WORK = 'ADD_TIME_WORKED_WORK';
export const ADD_TIME_WORKED_READ = 'ADD_TIME_WORKED_READ';
export const ADD_TIME_WORKED_MEDITATE = 'ADD_TIME_WORKED_MEDITATE';
export const ADD_TIME_WORKED_FAMILYTIME = 'ADD_TIME_WORKED_FAMILYTIME';
